### ISSUE TITLE
Android Build Error 3.2.1 

### ISSUE THREAD

**Issue by utkudenis** [Netvent/storyly-sdk#375]
I have just updated storyly 3.2.0 to 3.2.1 and there is a build error on the Android 

Execution failed for task ':storyly_flutter:generateReleaseRFile'.
> Could not resolve all files for configuration ':storyly_flutter:releaseCompileClasspath'.
   > Could not find com.appsamurai.storyly:storyly:3.2.1.
     Required by:
         project :storyly_flutter

Didn't you update android packages ?

**Comment by utkudenis** [comment]
3.2.1 not in maven  :( 
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.appsamurai.storyly:storyly:3.2.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/appsamurai/storyly/storyly/3.2.1/storyly-3.2.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/appsamurai/storyly/storyly/3.2.1/storyly-3.2.1.pom
     Required by:
         project :app > project :storyly_flutter

**Comment by yigcal** [comment]
Hi @utkudenis,

It is available now. Please check again.
