### ISSUE TITLE
Latest storyly-react-native using older SDK

### ISSUE THREAD

**Issue by vnvs** [Netvent/storyly-sdk#403]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

Latest version still using 3.6.3 as seen here
https://github.com/Netvent/storyly-sdk/blob/82255fec1ef8d8f6c18a54eb4377d7eb0a3048c7/react-native/storyly-react-native/android/build.gradle

## Environment Details
**Storyly SDK Version:** 3.10.0
**React Native SDK Version:** 0.73.6
**Platform:**
- [x] Android 
- [ ] iOS
**Device Model:** ---
**Device OS Version:** ---
**Additional Info:**

## Steps to Reproduce

1.
2.
3.
4.

**Comment by yigcal** [comment]
Hi @vnvs,

We’re currently maintaining the 3.x.x versions of our cross-platform frameworks from a separate branch on a temporary basis. You can see that the latest React Native v3.10.0 is using the native Android v3.10.0 at the following link:

https://github.com/Netvent/storyly-sdk/blob/storyly-v3.x.x/react-native/storyly-react-native/android/build.gradle

Thanks
